package interfaz;

import dominio.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author dariansaldana 230846
 */
public class VentanaMenuPrincipal extends javax.swing.JFrame {

    public VentanaMenuPrincipal(Sistema sis) {
        modelo = sis;
        initComponents();
        setTitle("Pantalla Principal - Autor: Darián Saldaña 230846");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClaroOscuro = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGestion = new javax.swing.JMenu();
        opcionGestionClientes = new javax.swing.JMenuItem();
        opcionGestionVehiculos = new javax.swing.JMenuItem();
        opcionGestionEmpleados = new javax.swing.JMenuItem();
        opcionGestionContratos = new javax.swing.JMenuItem();
        menuMovimientos = new javax.swing.JMenu();
        opcionEntradas = new javax.swing.JMenuItem();
        opcionSalidas = new javax.swing.JMenuItem();
        opcionServiciosAdicionales = new javax.swing.JMenuItem();
        menuVarios = new javax.swing.JMenu();
        opcionReportes = new javax.swing.JMenuItem();
        opcionGrabacionDatos = new javax.swing.JMenuItem();
        opcionRecuperacionDatos = new javax.swing.JMenuItem();
        opcionMinijuego = new javax.swing.JMenuItem();
        opcionInformacionAutor = new javax.swing.JMenuItem();
        menuTerminar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClaroOscuro.setText("Claro/Oscuro");
        getContentPane().add(btnClaroOscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        menuGestion.setText("Gestión");

        opcionGestionClientes.setText("Gestión de clientes ");
        opcionGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionGestionClientesActionPerformed(evt);
            }
        });
        menuGestion.add(opcionGestionClientes);

        opcionGestionVehiculos.setText("Gestión de vehículos");
        opcionGestionVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionGestionVehiculosActionPerformed(evt);
            }
        });
        menuGestion.add(opcionGestionVehiculos);

        opcionGestionEmpleados.setText("Gestión de empleados");
        opcionGestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionGestionEmpleadosActionPerformed(evt);
            }
        });
        menuGestion.add(opcionGestionEmpleados);

        opcionGestionContratos.setText("Gestión de contratos");
        opcionGestionContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionGestionContratosActionPerformed(evt);
            }
        });
        menuGestion.add(opcionGestionContratos);

        jMenuBar1.add(menuGestion);

        menuMovimientos.setText("Movimientos");

        opcionEntradas.setText("Entradas");
        opcionEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionEntradasActionPerformed(evt);
            }
        });
        menuMovimientos.add(opcionEntradas);

        opcionSalidas.setText("Salidas");
        opcionSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSalidasActionPerformed(evt);
            }
        });
        menuMovimientos.add(opcionSalidas);

        opcionServiciosAdicionales.setText("Servicios Adicionales");
        opcionServiciosAdicionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionServiciosAdicionalesActionPerformed(evt);
            }
        });
        menuMovimientos.add(opcionServiciosAdicionales);

        jMenuBar1.add(menuMovimientos);

        menuVarios.setText("Varios");

        opcionReportes.setText("Reportes");
        menuVarios.add(opcionReportes);

        opcionGrabacionDatos.setText("Grabación de datos");
        menuVarios.add(opcionGrabacionDatos);

        opcionRecuperacionDatos.setText("Recuperación de datos");
        menuVarios.add(opcionRecuperacionDatos);

        opcionMinijuego.setText("Minijuego");
        menuVarios.add(opcionMinijuego);

        opcionInformacionAutor.setText("Información de autor");
        menuVarios.add(opcionInformacionAutor);

        jMenuBar1.add(menuVarios);

        menuTerminar.setText("Terminar");
        jMenuBar1.add(menuTerminar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionGestionEmpleadosActionPerformed
        VentanaEmpleado vent = new VentanaEmpleado(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_opcionGestionEmpleadosActionPerformed

    private void opcionGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionGestionClientesActionPerformed
        VentanaCliente vent = new VentanaCliente(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_opcionGestionClientesActionPerformed

    private void opcionGestionVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionGestionVehiculosActionPerformed
        VentanaVehiculo vent = new VentanaVehiculo(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_opcionGestionVehiculosActionPerformed

    private void opcionGestionContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionGestionContratosActionPerformed
        VentanaContrato vent = new VentanaContrato(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_opcionGestionContratosActionPerformed

    private void opcionEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEntradasActionPerformed
        VentanaEntradaVehiculo vent = new VentanaEntradaVehiculo(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_opcionEntradasActionPerformed

    private void opcionSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSalidasActionPerformed
        VentanaSalidaVehiculo vent = new VentanaSalidaVehiculo(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_opcionSalidasActionPerformed

    private void opcionServiciosAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionServiciosAdicionalesActionPerformed
        VentanaServiciosAdicionales vent = new VentanaServiciosAdicionales(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_opcionServiciosAdicionalesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnClaroOscuro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenu menuTerminar;
    private javax.swing.JMenu menuVarios;
    private javax.swing.JMenuItem opcionEntradas;
    private javax.swing.JMenuItem opcionGestionClientes;
    private javax.swing.JMenuItem opcionGestionContratos;
    private javax.swing.JMenuItem opcionGestionEmpleados;
    private javax.swing.JMenuItem opcionGestionVehiculos;
    private javax.swing.JMenuItem opcionGrabacionDatos;
    private javax.swing.JMenuItem opcionInformacionAutor;
    private javax.swing.JMenuItem opcionMinijuego;
    private javax.swing.JMenuItem opcionRecuperacionDatos;
    private javax.swing.JMenuItem opcionReportes;
    private javax.swing.JMenuItem opcionSalidas;
    private javax.swing.JMenuItem opcionServiciosAdicionales;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
