package interfaz;

import Utilidades.TemaUI;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author dariansaldana 230846
 */
public class VentanaInformacionAutor extends javax.swing.JFrame {

    public VentanaInformacionAutor() {
        initComponents();
        TemaUI.aplicarTema(this);
        setTitle("Información del Autor");
        cargarDatosAutor();
    }

    private void cargarDatosAutor() {
        try {
            ImageIcon img = new ImageIcon(getClass().getResource("/interfaz/yo.jpg"));
            Image imagenEscalada = img.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
            lbl_imagen.setIcon(new ImageIcon(imagenEscalada));
        } catch (Exception e) {
            lbl_imagen.setText("Imagen no encontrada");
            System.out.println("error" + e);
        }

        lbl_info.setText("<html><div style='text-align:center;'>"
                + "<b>Darián Saldaña</b><br/>"
                + "Estudiante de Lic. en Sistemas<br/>"
                + "Número Estudiante: 230846<br/>"
                + "Email: dariansaldana730@gmail.com"
                + "</div></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_info = new javax.swing.JLabel();
        lbl_imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lbl_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 330, 240));

        lbl_imagen.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbl_imagenInputMethodTextChanged(evt);
            }
        });
        getContentPane().add(lbl_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 200, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_imagenInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbl_imagenInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_imagenInputMethodTextChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_imagen;
    private javax.swing.JLabel lbl_info;
    // End of variables declaration//GEN-END:variables
}
