package interfaz;

import dominio.*;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author dariansaldana 230846
 */
public class VentanaVehiculo extends javax.swing.JFrame implements Observer{

    public VentanaVehiculo(Sistema sis) {
        modelo = sis;
        modelo.addObserver(this);
        initComponents();
        cargarListas();
        setTitle("Gestión de Vehículos");

    }

    public void cargarListas() {
        listaVehiculosVehiculo.setListData(modelo.getListaVehiculos().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JTextField();
        lblVehiculos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaVehiculosVehiculo = new javax.swing.JList();
        btnVaciarVehiculo = new javax.swing.JButton();
        btnAgregarVehiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Matrícula");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 30));

        lblMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(lblMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 190, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Marca");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 30));

        lblMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 190, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Modelo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 30));

        lblModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblModeloActionPerformed(evt);
            }
        });
        getContentPane().add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 190, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Estado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 30));

        lblEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 190, 30));

        lblVehiculos.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblVehiculos.setText("Vehículos");
        getContentPane().add(lblVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 110, 30));

        listaVehiculosVehiculo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        listaVehiculosVehiculo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaVehiculosVehiculo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaVehiculosVehiculoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaVehiculosVehiculo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 200, 180));

        btnVaciarVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVaciarVehiculo.setText("Vaciar");
        btnVaciarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVaciarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, -1));

        btnAgregarVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarVehiculo.setText("Agregar");
        btnAgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMatriculaActionPerformed

    private void lblMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMarcaActionPerformed

    private void lblModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModeloActionPerformed

    private void lblEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEstadoActionPerformed

    private void listaVehiculosVehiculoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaVehiculosVehiculoValueChanged
        Vehiculo vehi = (Vehiculo) listaVehiculosVehiculo.getSelectedValue();
        if (vehi == null) {
            return;
        }
        lblMatricula.setText(vehi.getMatricula());
        lblMarca.setText(vehi.getMarca());
        lblModelo.setText(vehi.getModelo());
        lblEstado.setText(vehi.getEstado());
    }//GEN-LAST:event_listaVehiculosVehiculoValueChanged

    private void btnVaciarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarVehiculoActionPerformed
        lblMatricula.setText("");
        lblMarca.setText("");
        lblModelo.setText("");
        lblEstado.setText("");

        listaVehiculosVehiculo.clearSelection();
    }//GEN-LAST:event_btnVaciarVehiculoActionPerformed

    private void btnAgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVehiculoActionPerformed
        String matricula = lblMatricula.getText().trim();
        String marca = lblMarca.getText().trim();
        String modeloV = lblModelo.getText().trim();
        String estado = lblEstado.getText().trim();

        if (matricula.isEmpty() || marca.isEmpty() || modeloV.isEmpty() || estado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Vehiculo existente = modelo.buscarVehiculoPorMatricula(matricula);
        if (existente != null) {
            JOptionPane.showMessageDialog(this, "Ya existe un vehículo con esa matrícula.", "Matrícula duplicada", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Vehiculo nuevo = new Vehiculo(matricula, marca, modeloV, estado);
        modelo.agregarVehiculo(nuevo);
        btnVaciarVehiculoActionPerformed(null);
        JOptionPane.showMessageDialog(this, "Vehículo agregado con éxito.");
    }//GEN-LAST:event_btnAgregarVehiculoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVehiculo;
    private javax.swing.JButton btnVaciarVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblEstado;
    private javax.swing.JTextField lblMarca;
    private javax.swing.JTextField lblMatricula;
    private javax.swing.JTextField lblModelo;
    private javax.swing.JLabel lblVehiculos;
    private javax.swing.JList listaVehiculosVehiculo;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;

    @Override
    public void update(Observable o, Object arg) {
        cargarListas();
    }
}
