package interfaz;

import Utilidades.TemaUI;
import dominio.*;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;

/**
 *
 * @author dariansaldana 230846
 */
public class VentanaEntradaVehiculo extends javax.swing.JFrame implements Observer {

    public VentanaEntradaVehiculo(Sistema sis) {
        modelo = sis;
        modelo.addObserver(this);
        initComponents();
        TemaUI.aplicarTema(this);
        cargarListas();
        setTitle("Entrada de Vehículos");
    }

    private void cargarListas() {

        // Vehículos filtrando los que ya estan en el parking
        DefaultListModel modeloVehiculos = new DefaultListModel();
        for (Vehiculo v : modelo.getListaVehiculos()) {
            if (!modelo.vehiculoEstaEnParking(v)) {
                modeloVehiculos.addElement(v);
            }
        }
        listaVehiculosEntrada.setModel(modeloVehiculos);

        // Empleados
        DefaultListModel modeloEmpleados = new DefaultListModel();
        for (Empleado e : modelo.getListaEmpleados()) {
            modeloEmpleados.addElement(e);
        }
        listaEmpleadosEntrada.setModel(modeloEmpleados);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaVehiculosEntrada = new javax.swing.JList();
        lblVehiculos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEmpleadosEntrada = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHoraEntrada = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblFechaEntrada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaNotasEntrada = new javax.swing.JTextArea();
        btnEntradaVehiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaVehiculosEntrada.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        listaVehiculosEntrada.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaVehiculosEntrada.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaVehiculosEntradaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaVehiculosEntrada);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 240));

        lblVehiculos.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblVehiculos.setText("Vehículos");
        getContentPane().add(lblVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        listaEmpleadosEntrada.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        listaEmpleadosEntrada.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaEmpleadosEntrada.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaEmpleadosEntradaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaEmpleadosEntrada);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 170, 240));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Empleado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 120, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Notas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 50, 30));

        lblHoraEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblHoraEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(lblHoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 120, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Hora Ingreso");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 110, 30));

        lblFechaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFechaEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(lblFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 100, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Fecha Ingreso");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 100, 30));

        txtAreaNotasEntrada.setColumns(20);
        txtAreaNotasEntrada.setRows(5);
        jScrollPane3.setViewportView(txtAreaNotasEntrada);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 240, 160));

        btnEntradaVehiculo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnEntradaVehiculo.setText("Registrar Ingreso");
        btnEntradaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntradaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 327, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaVehiculosEntradaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaVehiculosEntradaValueChanged
        if (!evt.getValueIsAdjusting()) {
            Vehiculo vehiculoSeleccionado = (Vehiculo) listaVehiculosEntrada.getSelectedValue();
            if (vehiculoSeleccionado != null && modelo.vehiculoTieneContrato(vehiculoSeleccionado)) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "El vehículo seleccionado posee un contrato.",
                        "Aviso",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_listaVehiculosEntradaValueChanged

    private void listaEmpleadosEntradaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaEmpleadosEntradaValueChanged
    }//GEN-LAST:event_listaEmpleadosEntradaValueChanged

    private void lblHoraEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblHoraEntradaActionPerformed
    }//GEN-LAST:event_lblHoraEntradaActionPerformed

    private void lblFechaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFechaEntradaActionPerformed
    }//GEN-LAST:event_lblFechaEntradaActionPerformed

    private void btnEntradaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaVehiculoActionPerformed

        Vehiculo vehiculoSeleccionado = (Vehiculo) listaVehiculosEntrada.getSelectedValue();
        Empleado empleadoSeleccionado = (Empleado) listaEmpleadosEntrada.getSelectedValue();
        String fechaTexto = lblFechaEntrada.getText().trim();
        String horaTexto = lblHoraEntrada.getText().trim();
        String notas = txtAreaNotasEntrada.getText().trim();

        if (vehiculoSeleccionado == null || empleadoSeleccionado == null || fechaTexto.isEmpty() || horaTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios. Seleccione el vehículo que ingresa, "
                    + "el empleado que lo estaciona, en qué fecha y a qué hora.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar formato de hora HH:MM (24 horas)
        if (!horaTexto.matches("([01]\\d|2[0-3]):[0-5]\\d")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de hora inválido. Use HH:MM (24 hs)", "Atención", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar formato de fecha dd/MM/yyyy (opcional)
        if (!fechaTexto.matches("\\d{2}/\\d{2}/\\d{4}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use DD/MM/AAAA", "Atención", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar si el vehículo ya está en el parking
        if (modelo.vehiculoEstaEnParking(vehiculoSeleccionado)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ese vehículo ya está dentro del parking.", "Información", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Registrar la entrada del vehículo
        modelo.registrarEntradaVehiculo(vehiculoSeleccionado, empleadoSeleccionado, fechaTexto, horaTexto, notas);

        javax.swing.JOptionPane.showMessageDialog(this, "Vehículo ingresado al parking correctamente.");

        cargarListas();
        listaVehiculosEntrada.clearSelection();
        listaEmpleadosEntrada.clearSelection();
        lblFechaEntrada.setText("");
        lblHoraEntrada.setText("");
        txtAreaNotasEntrada.setText("");

        System.out.println("Historial de Entradas:");
        for (EntradaVehiculo entrada : modelo.getHistorialEntradas()) {
            System.out.println(" - " + entrada);
        }
    }//GEN-LAST:event_btnEntradaVehiculoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntradaVehiculo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lblFechaEntrada;
    private javax.swing.JTextField lblHoraEntrada;
    private javax.swing.JLabel lblVehiculos;
    private javax.swing.JList listaEmpleadosEntrada;
    private javax.swing.JList listaVehiculosEntrada;
    private javax.swing.JTextArea txtAreaNotasEntrada;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;

    @Override
    public void update(Observable o, Object arg) {
        cargarListas();
    }
}
