package interfaz;

import dominio.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;

/**
 *
 * @author dariansaldana 230846
 */
public class VentanaSalidaVehiculo extends javax.swing.JFrame {

    public VentanaSalidaVehiculo(Sistema sis) {
        modelo = sis;
        initComponents();
        cargarListas();
        setTitle("Salida de Vehículos");
    }

    private void cargarListas() {

        DefaultListModel modeloEntradas = new DefaultListModel();
        for (EntradaVehiculo entrada : modelo.getHistorialEntradas()) {
            if (!entrada.estaFinalizada()) {
                modeloEntradas.addElement(entrada);
            }
        }
        listaIngresosSalidaVehiculo.setModel(modeloEntradas);

        // Empleados
        DefaultListModel modeloEmpleados = new DefaultListModel();
        for (Empleado e : modelo.getListaEmpleados()) {
            modeloEmpleados.addElement(e);
        }
        listaEmpleadosSalida.setModel(modeloEmpleados);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalidaVehiculo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEmpleadosSalida = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblHoraSalida = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaComentariosSalida = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaIngresosSalidaVehiculo = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalidaVehiculo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSalidaVehiculo.setText("Registrar Salida");
        btnSalidaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalidaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 327, 240, 30));

        listaEmpleadosSalida.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        listaEmpleadosSalida.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaEmpleadosSalida.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaEmpleadosSalidaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaEmpleadosSalida);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 170, 240));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Empleado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 120, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Hora Salida");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 110, 30));

        lblHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblHoraSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(lblHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 120, 30));

        txtAreaComentariosSalida.setColumns(20);
        txtAreaComentariosSalida.setRows(5);
        jScrollPane3.setViewportView(txtAreaComentariosSalida);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 240, 160));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Comentarios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 120, 30));

        lblFechaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFechaSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(lblFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 100, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Fecha Salida");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 100, 30));

        listaIngresosSalidaVehiculo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        listaIngresosSalidaVehiculo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaIngresosSalidaVehiculo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaIngresosSalidaVehiculoValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listaIngresosSalidaVehiculo);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 240));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setText("Ingresos Actuales");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaEmpleadosSalidaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaEmpleadosSalidaValueChanged

    }//GEN-LAST:event_listaEmpleadosSalidaValueChanged

    private void lblHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblHoraSalidaActionPerformed

    }//GEN-LAST:event_lblHoraSalidaActionPerformed

    private void lblFechaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFechaSalidaActionPerformed

    }//GEN-LAST:event_lblFechaSalidaActionPerformed

    private void btnSalidaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaVehiculoActionPerformed
        EntradaVehiculo entradaSeleccionada = (EntradaVehiculo) listaIngresosSalidaVehiculo.getSelectedValue();
        Empleado empleadoSalida = (Empleado) listaEmpleadosSalida.getSelectedValue();
        String fechaSalidaTexto = lblFechaSalida.getText().trim();
        String horaSalidaTexto = lblHoraSalida.getText().trim();
        String comentario = txtAreaComentariosSalida.getText().trim();

        if (entradaSeleccionada == null || empleadoSalida == null || fechaSalidaTexto.isEmpty() || horaSalidaTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar formato hora
        if (!horaSalidaTexto.matches("([01]\\d|2[0-3]):[0-5]\\d")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de hora inválido. Use HH:MM (24 hs)", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar formato fecha
        if (!fechaSalidaTexto.matches("\\d{2}/\\d{2}/\\d{4}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use DD/MM/AAAA", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Parsear fecha y hora de entrada y salida
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        LocalDateTime fechaHoraEntrada = LocalDateTime.parse(entradaSeleccionada.getFecha() + " " + entradaSeleccionada.getHora(), formatter);
        LocalDateTime fechaHoraSalida;

        try {
            fechaHoraSalida = LocalDateTime.parse(fechaSalidaTexto + " " + horaSalidaTexto, formatter);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo interpretar fecha y hora de salida.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!fechaHoraSalida.isAfter(fechaHoraEntrada)) {
            javax.swing.JOptionPane.showMessageDialog(this, "La salida debe ser posterior a la entrada.", "Atención", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calcular duración
        Duration duracion = Duration.between(fechaHoraEntrada, fechaHoraSalida);
        long horas = duracion.toHours();
        long minutos = duracion.toMinutes() % 60;

        // Crear salida
        Vehiculo vehiculo = entradaSeleccionada.getVehiculo();
        SalidaVehiculo nuevaSalida = new SalidaVehiculo(vehiculo, empleadoSalida, fechaSalidaTexto, horaSalidaTexto, comentario);
        modelo.registrarSalidaVehiculo(entradaSeleccionada, nuevaSalida); // Esto lo implementamos ahora

        boolean tieneContrato = modelo.vehiculoTieneContrato(vehiculo);
        String infoContrato = tieneContrato ? "Este vehículo tiene contrato." : "Este vehículo no tiene contrato.";

        String mensaje = String.format("Salida registrada correctamente.\nTiempo en el parking: %d horas y %d minutos.\n%s", horas, minutos, infoContrato);
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Salida registrada", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        cargarListas();
        listaIngresosSalidaVehiculo.clearSelection();
        listaEmpleadosSalida.clearSelection();
        lblFechaSalida.setText("");
        lblHoraSalida.setText("");
        txtAreaComentariosSalida.setText("");

        System.out.println("Historial de Salidas:");
        for (SalidaVehiculo salida : modelo.getHistorialSalidas()) {
            System.out.println(" - " + salida);
        }
    }//GEN-LAST:event_btnSalidaVehiculoActionPerformed

    private void listaIngresosSalidaVehiculoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaIngresosSalidaVehiculoValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listaIngresosSalidaVehiculoValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalidaVehiculo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lblFechaSalida;
    private javax.swing.JTextField lblHoraSalida;
    private javax.swing.JList listaEmpleadosSalida;
    private javax.swing.JList listaIngresosSalidaVehiculo;
    private javax.swing.JTextArea txtAreaComentariosSalida;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
