package interfaz;

import dominio.*;
import javax.swing.JOptionPane;

/**
 *
 * @author dariansaldana 230846
 */
public class VentanaCliente extends javax.swing.JFrame {

    public VentanaCliente(Sistema sis) {
        modelo = sis;
        initComponents();
        cargarListas();
        setTitle("Gestión de Clientes");
    }

    public void cargarListas() {
        listaClientesCliente.setListData(modelo.getListaClientes().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JTextField();
        lblDireccionCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblCelularCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCedulaCliente = new javax.swing.JTextField();
        lblAñoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaClientesCliente = new javax.swing.JList();
        btnVaciarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Clientes");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 120, 30));

        lblNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblNombreClienteActionPerformed(evt);
            }
        });
        getContentPane().add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 190, 30));

        lblDireccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDireccionClienteActionPerformed(evt);
            }
        });
        getContentPane().add(lblDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 190, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Dirección");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 30));

        lblCelularCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCelularClienteActionPerformed(evt);
            }
        });
        getContentPane().add(lblCelularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 190, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Celular");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Cédula");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, 30));

        lblCedulaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCedulaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(lblCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 190, 30));

        lblAñoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblAñoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(lblAñoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Año");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 30));

        listaClientesCliente.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        listaClientesCliente.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaClientesCliente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaClientesClienteValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaClientesCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 200, 180));

        btnVaciarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVaciarCliente.setText("Vaciar");
        btnVaciarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnVaciarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 290, 90, -1));

        btnEliminarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 200, -1));

        btnAgregarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarCliente.setText("Agregar");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNombreClienteActionPerformed

    private void lblDireccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDireccionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDireccionClienteActionPerformed

    private void lblCelularClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCelularClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCelularClienteActionPerformed

    private void lblCedulaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCedulaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCedulaClienteActionPerformed

    private void lblAñoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAñoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAñoClienteActionPerformed

    private void btnVaciarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarClienteActionPerformed
        lblAñoCliente.setText("");
        lblCedulaCliente.setText("");
        lblCelularCliente.setText("");
        lblDireccionCliente.setText("");
        lblNombreCliente.setText("");

        listaClientesCliente.clearSelection();
        btnEliminarCliente.setEnabled(false);
    }//GEN-LAST:event_btnVaciarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        String cedula = lblCedulaCliente.getText().trim();

        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese una cédula.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cliente cliente = modelo.buscarClientePorCedula(cedula);
        if (cliente == null) {
            JOptionPane.showMessageDialog(this, "No se encontró un cliente con esa cédula.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Deseás eliminar al cliente?\n\n"
                + "Nombre: " + cliente.getNombre() + "\n"
                + "Cédula: " + cliente.getCedula(),
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            modelo.eliminarClientePorCedula(cedula);
            cargarListas(); // actualiza la lista visual
            btnVaciarClienteActionPerformed(null); // limpia los campos
            JOptionPane.showMessageDialog(this, "Cliente eliminado con éxito.");
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        String nombre = lblNombreCliente.getText().trim();
        String direccion = lblDireccionCliente.getText().trim();
        String celular = lblCelularCliente.getText().trim();
        String cedula = lblCedulaCliente.getText().trim();
        String año = lblAñoCliente.getText().trim();

        if (nombre.isEmpty() || direccion.isEmpty() || celular.isEmpty() || cedula.isEmpty() || año.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cliente existente = modelo.buscarClientePorCedula(cedula);
        if (existente != null) {
            JOptionPane.showMessageDialog(this, "Ya existe un cliente con esa cédula.", "Cédula duplicada", JOptionPane.ERROR_MESSAGE);
            return;
        }

        modelo.agregarCliente(new Cliente(nombre, direccion, celular, cedula, año));
        cargarListas();
        btnVaciarClienteActionPerformed(null);
        JOptionPane.showMessageDialog(this, "Cliente agregado con éxito.");
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void listaClientesClienteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaClientesClienteValueChanged
        Cliente cli = (Cliente) listaClientesCliente.getSelectedValue();
        if (cli == null) {
            btnEliminarCliente.setEnabled(false);
            return;
        }
        lblNombreCliente.setText(cli.getNombre());
        lblDireccionCliente.setText(cli.getDireccion());
        lblCelularCliente.setText(cli.getCelular());
        lblCedulaCliente.setText(cli.getCedula());
        lblAñoCliente.setText(cli.getAño());

        btnEliminarCliente.setEnabled(true);

    }//GEN-LAST:event_listaClientesClienteValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnVaciarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblAñoCliente;
    private javax.swing.JTextField lblCedulaCliente;
    private javax.swing.JTextField lblCelularCliente;
    private javax.swing.JTextField lblDireccionCliente;
    private javax.swing.JTextField lblNombreCliente;
    private javax.swing.JList listaClientesCliente;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
