package interfaz;

import Utilidades.TemaUI;
import dominio.*;
import java.awt.GridLayout;
import java.util.Observable;
import java.util.Observer;
import javax.swing.*;

/**
 *
 * @author dariansaldana 230846
 */
public class VentanaContrato extends javax.swing.JFrame implements Observer {

    public VentanaContrato(Sistema sis) {
        modelo = sis;
        modelo.addObserver(this);
        initComponents();
        TemaUI.aplicarTema(this);
        cargarListas();
        setTitle("Gestión de Contratos");
    }

    private void actualizarListaContratos() {
        DefaultListModel modeloLista = new DefaultListModel();
        for (Contrato contrato : modelo.getListaContratos()) {
            modeloLista.addElement(contrato);
        }
        listaContratosExistentes.setModel(modeloLista);
    }

    private void cargarListas() {
        // Clientes
        DefaultListModel modeloClientes = new DefaultListModel();
        for (Cliente c : modelo.getListaClientes()) {
            modeloClientes.addElement(c);
        }
        listaClientesContrato.setModel(modeloClientes);

        // Vehículos
        DefaultListModel modeloVehiculos = new DefaultListModel();
        for (Vehiculo v : modelo.getListaVehiculos()) {
            modeloVehiculos.addElement(v);
        }
        listaVehiculosContrato.setModel(modeloVehiculos);

        // Empleados
        DefaultListModel modeloEmpleados = new DefaultListModel();
        for (Empleado e : modelo.getListaEmpleados()) {
            modeloEmpleados.addElement(e);
        }
        listaEmpleadosContrato.setModel(modeloEmpleados);

        // Contratos existentes
        actualizarListaContratos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblValorMensualContrato = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCrearContrato = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaContratosExistentes = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaClientesContrato = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaVehiculosContrato = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaEmpleadosContrato = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Vehículo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, 50));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Valor Mensual");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, 50));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Contratos Existentes");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 240, 50));

        lblValorMensualContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblValorMensualContratoActionPerformed(evt);
            }
        });
        getContentPane().add(lblValorMensualContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 140, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Empleado");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 70, 50));

        btnCrearContrato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrearContrato.setText("Crear Contrato");
        btnCrearContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearContratoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 200, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setText("Cliente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 50));

        listaContratosExistentes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaContratosExistentes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaContratosExistentesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaContratosExistentes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 230, 240));

        listaClientesContrato.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaClientesContrato);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, 170));

        listaVehiculosContrato.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaVehiculosContrato);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 160, 170));

        listaEmpleadosContrato.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listaEmpleadosContrato);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 140, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearContratoActionPerformed
        Cliente cliente = (Cliente) listaClientesContrato.getSelectedValue();
        Vehiculo vehiculo = (Vehiculo) listaVehiculosContrato.getSelectedValue();
        Empleado empleado = (Empleado) listaEmpleadosContrato.getSelectedValue();

        if (cliente == null || vehiculo == null || empleado == null || lblValorMensualContrato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double valorMensual = Double.parseDouble(lblValorMensualContrato.getText());

            if (modelo.vehiculoYaContratado(vehiculo)) {
                JOptionPane.showMessageDialog(this, "Este vehículo ya está asociado a un contrato.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Contrato contrato = new Contrato(cliente, vehiculo, empleado, valorMensual);
            modelo.agregarContrato(contrato);
            JOptionPane.showMessageDialog(this, "Contrato creado con éxito.");
            actualizarListaContratos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor mensual válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearContratoActionPerformed

    private void lblValorMensualContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblValorMensualContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblValorMensualContratoActionPerformed

    private void listaContratosExistentesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaContratosExistentesValueChanged
        if (!evt.getValueIsAdjusting()) {
            Contrato contrato = (Contrato) listaContratosExistentes.getSelectedValue();
            if (contrato != null) {
                JPanel panel = new JPanel();
                panel.setLayout(new GridLayout(0, 1, 5, 5));

                panel.add(new JLabel("ID del Contrato: " + contrato.getId()));
                panel.add(new JLabel("Cliente: " + contrato.getCliente().getNombre()));
                panel.add(new JLabel("Cédula: " + contrato.getCliente().getCedula()));
                panel.add(new JLabel("Vehículo: " + contrato.getVehiculo().getMatricula()));
                panel.add(new JLabel("Marca: " + contrato.getVehiculo().getMarca()));
                panel.add(new JLabel("Empleado: " + contrato.getEmpleado().getNombre()));
                panel.add(new JLabel("Valor Mensual: $" + contrato.getValorMensual()));

                JOptionPane.showMessageDialog(this, panel, "Detalle del Contrato", JOptionPane.INFORMATION_MESSAGE);
            }
        }    }//GEN-LAST:event_listaContratosExistentesValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearContrato;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField lblValorMensualContrato;
    private javax.swing.JList listaClientesContrato;
    private javax.swing.JList listaContratosExistentes;
    private javax.swing.JList listaEmpleadosContrato;
    private javax.swing.JList listaVehiculosContrato;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;

    @Override
    public void update(Observable o, Object arg) {
        cargarListas();
    }
}
