package interfaz;

import Utilidades.TemaUI;
import dominio.*;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;

/**
 *
 * @author dariansaldana 230846
 */
public class VentanaServiciosAdicionales extends javax.swing.JFrame implements Observer {

    public VentanaServiciosAdicionales(Sistema sis) {
        modelo = sis;
        modelo.addObserver(this);
        initComponents();
        cargarListas();
        TemaUI.aplicarTema(this);
        setTitle("Servicios Adicionales");
    }

    private void cargarListas() {
        // Vehículos activos en el estacionamiento
        DefaultListModel<Vehiculo> modeloVehiculos = new DefaultListModel<>();
        for (EntradaVehiculo entrada : modelo.getHistorialEntradas()) {
            if (!entrada.estaFinalizada()) {
                modeloVehiculos.addElement(entrada.getVehiculo());
            }
        }
        listaVehiculosServicios.setModel(modeloVehiculos);

        // Empleados
        DefaultListModel<Empleado> modeloEmpleados = new DefaultListModel<>();
        for (Empleado e : modelo.getListaEmpleados()) {
            modeloEmpleados.addElement(e);
        }
        listaEmpleadosServicios.setModel(modeloEmpleados);

        // Tipos de servicio
        selectServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Lavado", "Cambio de rueda", "Limpieza de tapizado", "Cambio de luces", "Otro"
        }));

        // Servicios registrados
        DefaultListModel<ServicioAdicional> modeloServicios = new DefaultListModel<>();
        for (ServicioAdicional s : modelo.getServiciosAdicionales()) {
            modeloServicios.addElement(s);
        }
        listaServiciosExistentes.setModel(modeloServicios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectServicios = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        lblVehiculos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFechaServicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblHoraServicio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaServiciosExistentes = new javax.swing.JList();
        lblVehiculos1 = new javax.swing.JLabel();
        lblCostoServicioAdicional = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrarServicio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaVehiculosServicios = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaEmpleadosServicios = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectServicios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectServiciosActionPerformed(evt);
            }
        });
        getContentPane().add(selectServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 230, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione un servicio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 190, -1));

        lblVehiculos.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblVehiculos.setText("Vehículos");
        getContentPane().add(lblVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Empleados");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 120, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Fecha");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 100, 30));

        lblFechaServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFechaServicioActionPerformed(evt);
            }
        });
        getContentPane().add(lblFechaServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 100, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Hora");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 110, 30));

        lblHoraServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblHoraServicioActionPerformed(evt);
            }
        });
        getContentPane().add(lblHoraServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 100, 30));

        listaServiciosExistentes.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        listaServiciosExistentes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaServiciosExistentes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaServiciosExistentesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaServiciosExistentes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 290, 110));

        lblVehiculos1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblVehiculos1.setText("Servicios");
        getContentPane().add(lblVehiculos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 230, -1));

        lblCostoServicioAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCostoServicioAdicionalActionPerformed(evt);
            }
        });
        getContentPane().add(lblCostoServicioAdicional, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 140, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Costo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 60, 50));

        btnRegistrarServicio.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnRegistrarServicio.setText("Registrar Servicio");
        btnRegistrarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarServicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 230, 30));

        listaVehiculosServicios.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        listaVehiculosServicios.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaVehiculosServicios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaVehiculosServiciosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaVehiculosServicios);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 140));

        listaEmpleadosServicios.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        listaEmpleadosServicios.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaEmpleadosServicios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaEmpleadosServiciosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaEmpleadosServicios);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 180, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectServiciosActionPerformed

    private void lblFechaServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFechaServicioActionPerformed

    }//GEN-LAST:event_lblFechaServicioActionPerformed

    private void lblHoraServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblHoraServicioActionPerformed

    }//GEN-LAST:event_lblHoraServicioActionPerformed

    private void listaServiciosExistentesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaServiciosExistentesValueChanged
        if (!evt.getValueIsAdjusting()) {
            ServicioAdicional servicioSeleccionado = (ServicioAdicional) listaServiciosExistentes.getSelectedValue();
            if (servicioSeleccionado != null) {
                String mensaje = "Servicio: " + servicioSeleccionado.getTipoServicio()
                        + "\nFecha: " + servicioSeleccionado.getFecha()
                        + "\nHora: " + servicioSeleccionado.getHora()
                        + "\nVehículo: " + servicioSeleccionado.getVehiculo().getMatricula() + " " + servicioSeleccionado.getVehiculo().getMarca()
                        + "\nEmpleado: " + servicioSeleccionado.getEmpleado().getNombre()
                        + "\nCosto: $" + servicioSeleccionado.getCosto();

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        mensaje,
                        "Detalle del Servicio",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_listaServiciosExistentesValueChanged

    private void lblCostoServicioAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCostoServicioAdicionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCostoServicioAdicionalActionPerformed

    private void btnRegistrarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarServicioActionPerformed
        Vehiculo vehiculoSeleccionado = (Vehiculo) listaVehiculosServicios.getSelectedValue();
        Empleado empleadoSeleccionado = (Empleado) listaEmpleadosServicios.getSelectedValue();
        String tipoServicio = (String) selectServicios.getSelectedItem();
        String fechaTexto = lblFechaServicio.getText().trim();
        String horaTexto = lblHoraServicio.getText().trim();
        String costoTexto = lblCostoServicioAdicional.getText().trim();

        if (vehiculoSeleccionado == null || empleadoSeleccionado == null
                || fechaTexto.isEmpty() || horaTexto.isEmpty() || costoTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios. Seleccione el vehículo, el empleado, la fecha, hora y costo del servicio.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar formato de hora HH:MM (24 hs)
        if (!horaTexto.matches("([01]\\d|2[0-3]):[0-5]\\d")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de hora inválido. Use HH:MM (24 hs).",
                    "Atención", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar formato de fecha DD/MM/AAAA
        if (!fechaTexto.matches("\\d{2}/\\d{2}/\\d{4}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use DD/MM/AAAA.",
                    "Atención", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar costo numérico positivo
        double costo;
        try {
            costo = Double.parseDouble(costoTexto);
            if (costo < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El costo debe ser un número positivo.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear y registrar el servicio
        ServicioAdicional nuevo = new ServicioAdicional(tipoServicio, fechaTexto, horaTexto, vehiculoSeleccionado, empleadoSeleccionado, costo);
        modelo.registrarServicioAdicional(nuevo);

        javax.swing.JOptionPane.showMessageDialog(this, "Servicio registrado correctamente.");

        // Actualizar lista de servicios
        DefaultListModel<ServicioAdicional> modeloServicios = new DefaultListModel<>();
        for (ServicioAdicional s : modelo.getServiciosAdicionales()) {
            modeloServicios.addElement(s);
        }
        listaServiciosExistentes.setModel(modeloServicios);

        // Limpiar campos
        listaVehiculosServicios.clearSelection();
        listaEmpleadosServicios.clearSelection();
        lblFechaServicio.setText("");
        lblHoraServicio.setText("");
        lblCostoServicioAdicional.setText("");
        selectServicios.setSelectedIndex(0);
    }//GEN-LAST:event_btnRegistrarServicioActionPerformed

    private void listaVehiculosServiciosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaVehiculosServiciosValueChanged
        if (!evt.getValueIsAdjusting()) {
            Vehiculo vehiculoSeleccionado = (Vehiculo) listaServiciosExistentes.getSelectedValue();
            if (vehiculoSeleccionado != null && modelo.vehiculoTieneContrato(vehiculoSeleccionado)) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "El vehículo seleccionado posee un contrato.",
                        "Aviso",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_listaVehiculosServiciosValueChanged

    private void listaEmpleadosServiciosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaEmpleadosServiciosValueChanged

    }//GEN-LAST:event_listaEmpleadosServiciosValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lblCostoServicioAdicional;
    private javax.swing.JTextField lblFechaServicio;
    private javax.swing.JTextField lblHoraServicio;
    private javax.swing.JTextField lblValorMensualContrato;
    private javax.swing.JTextField lblValorMensualContrato1;
    private javax.swing.JTextField lblValorMensualContrato2;
    private javax.swing.JLabel lblVehiculos;
    private javax.swing.JLabel lblVehiculos1;
    private javax.swing.JList listaEmpleadosServicios;
    private javax.swing.JList listaServiciosExistentes;
    private javax.swing.JList listaVehiculosServicios;
    private javax.swing.JComboBox selectServicios;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;

    @Override
    public void update(Observable o, Object arg) {
        cargarListas();
    }
}
