package interfaz;

import Utilidades.TemaUI;
import dominio.*;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author dariansaldana 230846
 */
public class VentanaEmpleado extends javax.swing.JFrame implements Observer {

    public VentanaEmpleado(Sistema sis) {
        modelo = sis;
        modelo.addObserver(this);
        initComponents();
        TemaUI.aplicarTema(this);
        cargarLista();
        setTitle("Gestión de Empleados");
    }

    public void cargarLista() {
        listaEmpleadosEmpleado.setListData(modelo.getListaEmpleados().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombreEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblCedulaEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmpleadosEmpleado = new javax.swing.JList();
        btnVaciarEmpleado = new javax.swing.JButton();
        btnAgregarEmpleado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblDireccionEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblNroEmpleado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 30));

        lblNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblNombreEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(lblNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Cédula");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 30));

        lblCedulaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCedulaEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(lblCedulaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 190, 30));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Empleados");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 120, 30));

        listaEmpleadosEmpleado.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        listaEmpleadosEmpleado.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaEmpleadosEmpleado.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaEmpleadosEmpleadoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaEmpleadosEmpleado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 200, 180));

        btnVaciarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVaciarEmpleado.setText("Vaciar");
        btnVaciarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVaciarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 290, 90, -1));

        btnAgregarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarEmpleado.setText("Agregar");
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 100, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Dirección");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 30));

        lblDireccionEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDireccionEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(lblDireccionEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 190, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Nro. Empleado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 30));

        lblNroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblNroEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(lblNroEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 190, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNombreEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNombreEmpleadoActionPerformed

    private void lblCedulaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCedulaEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCedulaEmpleadoActionPerformed

    private void listaEmpleadosEmpleadoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaEmpleadosEmpleadoValueChanged
        Empleado emp = (Empleado) listaEmpleadosEmpleado.getSelectedValue();
        if (emp == null) {
            return;
        }

        lblNombreEmpleado.setText(emp.getNombre());
        lblCedulaEmpleado.setText(emp.getCedula());
        lblDireccionEmpleado.setText(emp.getDireccion());
        lblNroEmpleado.setText(emp.getNumeroEmpleado());
    }//GEN-LAST:event_listaEmpleadosEmpleadoValueChanged

    private void btnVaciarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarEmpleadoActionPerformed
        lblNombreEmpleado.setText("");
        lblCedulaEmpleado.setText("");
        lblDireccionEmpleado.setText("");
        lblNroEmpleado.setText("");
        listaEmpleadosEmpleado.clearSelection();
    }//GEN-LAST:event_btnVaciarEmpleadoActionPerformed

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        String nombre = lblNombreEmpleado.getText().trim();
        String cedula = lblCedulaEmpleado.getText().trim();
        String direccion = lblDireccionEmpleado.getText().trim();
        String nroEmpleado = lblNroEmpleado.getText().trim();

        if (nombre.isEmpty() || cedula.isEmpty() || direccion.isEmpty() || nroEmpleado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Empleado existente = modelo.buscarEmpleadoPorCedula(cedula);
        if (existente != null) {
            JOptionPane.showMessageDialog(this, "Ya existe un empleado con esa cédula.", "Cédula duplicada", JOptionPane.ERROR_MESSAGE);
            return;
        }

        modelo.agregarEmpleado(new Empleado(nombre, cedula, direccion, nroEmpleado));
        btnVaciarEmpleadoActionPerformed(null);
        JOptionPane.showMessageDialog(this, "Empleado agregado con éxito.");

    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void lblDireccionEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDireccionEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDireccionEmpleadoActionPerformed

    private void lblNroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNroEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNroEmpleadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnVaciarEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblCedulaEmpleado;
    private javax.swing.JTextField lblDireccionEmpleado;
    private javax.swing.JTextField lblNombreEmpleado;
    private javax.swing.JTextField lblNroEmpleado;
    private javax.swing.JList listaEmpleadosEmpleado;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;

    @Override
    public void update(Observable o, Object arg) {
        cargarLista();
    }
}
